name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Probe runner package cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: imagemagick cargo fonts-noto-cjk
          version: 1.0

      - name: Install oxipng from crates.io
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: oxipng

      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: just

      - name: Install typst-test from github
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: typst-test
          git: https://github.com/tingerrr/typst-test.git
          branch: ci-semi-stable

      - name: Setup typst
        uses: yusancky/setup-typst@v2
        with:
          version: 'v0.11.0'

      - name: Run test suite
        run: just ci
